//frontend\src\constants\financeCategories.js
export const FINANCE_CATEGORIES = [
  {
    value: "plate_collection",
    amharic: "መባ",
    english: "Plate Collection",
    color: "green",
    icon: "🙏",
  },
  {
    value: "tithe",
    amharic: "አስራት",
    english: "Tithe",
    color: "blue",
    icon: "💰",
  },
  {
    value: "candle_sale",
    amharic: "ሻማ",
    english: "Candle Sale",
    color: "orange",
    icon: "🕯️",
  },
  {
    value: "building_fund",
    amharic: "የቤተክርስቲያን ማሰሪያ",
    english: "Building Fund",
    color: "purple",
    icon: "🏛️",
  },
  {
    value: "charity_fund",
    amharic: "በጎ አድራጎት",
    english: "Charity Fund",
    color: "teal",
    icon: "❤️",
  },
  {
    value: "pledge",
    amharic: "ቃል የተገባ",
    english: "Pledge",
    color: "yellow",
    icon: "📝",
  },
  {
    value: "memorial_service",
    amharic: "ፍታት",
    english: "Memorial Service",
    color: "gray",
    icon: "🕊️",
  },
  {
    value: "wedding_engagement",
    amharic: "ጋብቻ / ቀለበት",
    english: "Wedding",
    color: "pink",
    icon: "💍",
  },
  {
    value: "baptism",
    amharic: "ክርስትና",
    english: "Baptism",
    color: "cyan",
    icon: "💧",
  },
  {
    value: "auction",
    amharic: "ጨረታ",
    english: "Auction",
    color: "indigo",
    icon: "🏷️",
  },
  {
    value: "other_fund",
    amharic: "ሌላ",
    english: "Other",
    color: "gray",
    icon: "📦",
  },
  {
    value: "sunday_cash_collection",
    amharic: "የእሁድ ስብስብ",
    english: "Sunday Collection",
    color: "gold",
    icon: "⛪",
  },
];